services:
  tailscale-services:
    image: docker.io/tailscale/tailscale:latest
    hostname: tailscale-services
    container_name: tailscale-services
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ./data:/var/lib/tailscale
      - ./entrypoint.sh:/entrypoint.sh:ro
      - ./services.json:/services.json:ro
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped
    # command: ["/entrypoint.sh"]
